# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.define :linux_vm do |config|
        config.vm.box = "hashicorp/precise64"
        config.vm.box_url = "http://files.vagrantup.com/precise64.box"
        config.vm.box_check_update = false
        config.vm.network :forwarded_port, guest: 5858, host: 58588
        config.vm.network :forwarded_port, guest: 3306, host: 33066

        config.vm.provision :file do |file|
            file.source = "install.sh"
            file.destination = "~/install.sh"
        end

        config.vm.provision  "fix-no-tty", type: "shell" do |s|
            s.privileged = false
            s.inline = "sudo sed -i '/tty/!s/mesg n/tty -s \\&\\& mesg n/' /root/.profile"
            s.inline = "sudo ~/install.sh"
        end

        config.vm.synced_folder "../codebase", "/codebase", :mount_options => ["dmode=777", "fmode=666"]
        config.vm.network "private_network", ip: "10.10.10.10" 
    end
end